### ISSUE TITLE
Could not compile because of errors in ta_NVI.c and ta_PVI.c

### ISSUE THREAD

**Issue by euyuil** [trufanov-nok/ta-lib-rt#1]
Hi Alexander,

I was on [the currently latest `master` branch](https://github.com/trufanov-nok/ta-lib-rt/commit/edde7514b921b9cdbecb1a25b888ca3345e372cf). And I ran the following to compile the branch:
```
~/ta-lib-rt$ cmake ta-lib
~/ta-lib-rt$ make
```
The `make` command reported that there were errors in the file `ta_NVI.c` and `ta_PVI.c`. I looked into those files and found there are some lines contain `%%%GENCODE%%%` which looks like some misplaced template placeholders.

I tried to remove the lines after [197 of `ta_NVI.c`](https://github.com/trufanov-nok/ta-lib-rt/blob/d955030d5e9e903944bba39aac82fa94b0e00f45/ta-lib/c/src/ta_func/ta_NVI.c#L197) and the lines after [197 of `ta_PVI.c`](https://github.com/trufanov-nok/ta-lib-rt/blob/d955030d5e9e903944bba39aac82fa94b0e00f45/ta-lib/c/src/ta_func/ta_PVI.c#L197). Then I reran the `make` command. The branch was built successfully.

I was using Ubuntu 16.04 LTS x64. Please let me know if there's anything else I can provide or help.

Thanks and regards,
Liu Yue

**Comment by trufanov-nok** [comment]
Hi, Liu Yue

It seems I've forget to exclude these files from CMakeLists. If you check my origin branch or take a look into TA-Lib official sources [here](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_NVI.c#l145) you'll see that they have a dummy implementation. So TA-Lib doesn't have these ta funcs implemented in reality although they are listed in documentation. So I didn't port them but seems to left the code to clear up with this later and forget about it. Perhaps I need to reimplement them or just remove from project. During development I've used QtCreator IDE and its toolchain so I missed cmake problem.

You can try to build it via Qt project [here](https://github.com/trufanov-nok/ta-lib-rt/tree/master/ta-lib/c/ide/qt/lib_proj/ta_lib) (there shouldn't be any Qt libraries dependencies included - I'm using it only as convenient IDE for linux) or give me some time to fix cmake toolchain. The results of compilation should appear in `ta-lib/c/lib/`

**Comment by trufanov-nok** [comment]
Ok, I've enabled generation of these functions, but they still lack implementation. i'll add it shortly - these indicators seems to be simple. Anyway now project can be build via cmake:
```
/ta-lib$ git pull
/ta-lib$ cd ta-lib
/ta-lib/ta-lib$ mkdir build && cd build
/ta-lib/ta-lib/build$ cmake ..
...
/ta-lib/ta-lib/build$ make
...
[ 99%] Building C object c/CMakeFiles/ta_lib.dir/src/ta_abstract/tables/table_m.c.o
[100%] Linking C shared library ../lib/libta_lib.so
[100%] Built target ta_lib
/ta-lib/ta-lib/build$
```
