### ISSUE TITLE
MIDPRICE, MIDPOINT returns wrong(?) values

### ISSUE THREAD

**Issue by mdukaczewski** [trufanov-nok/ta-lib-rt#10]
```
    data = np.asarray([1,2,3,4,5], dtype=np.float64)
    _, state = talibrt.MIDPOINT_StateInit(timeperiod=2)
    _, val_talibrt = talibrt.MIDPOINT_BatchState(state, data)
    val_talib = talib.MIDPOINT(data, timeperiod=2)
    print("talib", val_talib, "talibrt", val_talibrt)
```
returns
`talib [nan 1.5 2.5 3.5 4.5] talibrt [nan 1.5 2.  2.5 3. ]`

**Comment by trufanov-nok** [comment]
Thanks, I'll check

**Comment by trufanov-nok** [comment]
Indeed, that was a bug. Looks like I misunderstand the original code and as these indicators are very simple they are not covered by regtests. Should be fixed now. Could you doublecheck?

**Comment by mdukaczewski** [comment]
It looks good now. The same results as original talib. Good job :)
