### ISSUE TITLE
check volume != 0 is not valid

### ISSUE THREAD

**Issue by mdukaczewski** [trufanov-nok/ta-lib-rt#11]
There are volume checks for example in function ADOSC or OBV: volume can't be 0 at any given point which might not be a valid check If we have 1 minute bars of stock of some smaller company, often there wasn't any trades in the particular minute so volume == 0 should be accepted. And is accepted in original talib library.

```
    closes = np.asarray( [2,2,2], dtype=np.float64)
    volumes = np.asarray([100,0, 100], dtype=np.float64)
    val_talib = talib.OBV(closes, volumes)
    print("talib", val_talib)
    _, state = talibrt.OBV_StateInit()
    _, val_talibrt = talibrt.OBV_BatchState(state, closes, volumes)
```
returns
```
talib [100. 100. 100.]
Exception: TA_OBV_BatchState function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
```

**Comment by trufanov-nok** [comment]
That's a bug too. Seems autogenerated checks that test input arrays on NULL were generated for State functions and now check input price data on 0's. Shall fix and regenerate the code.
