### ISSUE TITLE
NaN issues

### ISSUE THREAD

**Issue by euyuil** [trufanov-nok/ta-lib-rt#2]
Hi Alexander,

Thanks for actively maintaining the project :-)

And I just found another issue. I'm not sure if it is worth a fix. But if you agree, I think I can help contribute to it.

Here is an example how we can see the issue:

```c
double NaN = std::numeric_limits<double>::quiet_NaN();
double pClosePrice[] =
{
    10.0, 10.0, 10.0, 10.0, 10.0, NaN, 10.0 /* hundreds of 10.0s */
};

struct TA_SMA_State *pState;
TA_SMA_StateInit(&pState, 5);
for (int i = 0; i < 100; ++i)
{
    double SMA;
    int nResult = TA_SMA_State(pState, pClosePrice[i], &SMA);
    if (nResult == TA_SUCCESS)
    {
        if (std::isnan(SMA))
        {
            std::printf("NaN ");
        }
        else
        {
            std::printf("%.1lf ", SMA);
        }
    }
    else if (nResult == TA_NEED_MORE_DATA)
    {
        // Do not print because the data is not enough.
    }
    else
    {
        // Code is not expected to go here.
        std::printf("ERROR ");
    }
}

TA_SMA_StateFree(&pState);
```

The output of the program is:

```
10.0 NaN NaN NaN NaN NaN NaN NaN ... (the following numbers are all NaNs)
```

But I thought the following output is more appropriate:

```
10.0 NaN NaN NaN NaN NaN 10.0 10.0 ... (the following numbers are all 10.0s)
```

I believe the reason we get this result is because when the `NaN` came to the window, it was added to `struct TA_SMA_State::periodTotal` and the result is `NaN`. Later when the `NaN` went out of the window, `NaN` was subtracted from `struct TA_SMA_State::periodTotal`, and the result is still `NaN`.

And I think there might be other indicators, for example, WMA, are also impacted by this NaN issue. And for some of the indicators, for example, EMA, the NaN will impact the result all the time.

Do you think if we can have any fix for this?

Regards,
Liu, Yue

**Comment by trufanov-nok** [comment]
Thank you for your feedback!
I think I would leave it as is...  The [original TA-Lib code](https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib/c/src/ta_func/ta_SMA.c#L275) should have same problem as there is no `isnan()` checks and same approach for rolling values calculation. So processing of NaNs and INFs is left on user side. If I fix this in new "state functions" their behavior will be inconsistent with the old "array functions". And fixing this in both TA implementations will require inserting of `if`s `isnan()`s and perhaps `isinf()`s in a tight array processing loops of original code. This might affect performance (i think there also should be some performance tricks made by compiler and CPU if data processing loops are tight and simple). I'm not worried about "state" functions performance as they are designed for different purpose, but would prefer to keep original code performance on original level. So function behavior consistence + performance + amount of work makes fixing NaN problem not viable...
So lets left NaN processing on user side.

**Comment by euyuil** [comment]
The reason why I proposed the change is because the change looks like mathematically correct, although the implementation will be more complicated and the performance will be worse... The processing of `NaN`s on user side is easier and I think users are supposed to do pre-processing for the `NaN`s case by case. For example, they might want to remove the `NaN`s, or fill in them with default value or previous value. It's good to keep it as is, and I suggest to document this behavior for the users :-)

**Comment by trufanov-nok** [comment]
> It's good to keep it as is, and I suggest to document this behavior for the users :-)

Good idea. I've created a wiki page for this: https://github.com/trufanov-nok/ta-lib-rt/wiki/Known-issues-and-limitations
