### ISSUE TITLE
Retrieving defaults

### ISSUE THREAD

**Issue by sunpavlik** [trufanov-nok/ta-lib-rt#6]
Hello,
Is there a way to retrieve optional parameter defaults kind of the same way as getting the list of input and output parameters?

Thank you,
Pavel

**Comment by trufanov-nok** [comment]
Take a look at `TA_GetOptInputParameterInfo()` and `TA_OptInputParameterInfo` struct. There is `defaultValue` field.

**Comment by sunpavlik** [comment]
perfect, thank you
