### ISSUE TITLE
Updating last data point without incrementing number of data points and recalculate

### ISSUE THREAD

**Issue by sunpavlik** [trufanov-nok/ta-lib-rt#7]
Hello,
The Lib is working great and was wondering if it was possible to update the last data without incrementing number of data points?

Thank you

**Comment by trufanov-nok** [comment]
Hi,
I'm not sure if I understand your question right. Could you provide some details about what you want to achieve?

**Comment by sunpavlik** [comment]
sure, let's say we have a SUM function which is initialized and we are just adding data points:

1)
Data point #1 = 6
set input variable to 6 and call: TA_CallFuncState
=> result = 6

2)
Data point #2 = 3
set input variable to 3 and call: TA_CallFuncState
=> result = 9

3)
Update Data point #2 from 3 to 8
set input variable to 8 and call: TA_CallFuncUpdateLastState
=> result = 14

Instead of adding new data point the last data point is updated.

**Comment by trufanov-nok** [comment]
Well, technically you need a copy of state after point 1. then call FuncState() for updated point 2 with this copy. But you have only pointer to the state on user side and don't know the structure of the state, so don't know the size of memory block to copy. Right now you could use:
 
> void* _state; // we assume it's initialized already
> FILE* _file; // open new file here
> TA_SUM_StateSave( _state ,  _file );
> void* _state_copy;
> fseek(_file, 0);
> TA_SUM_StateLoad( &_state_copy ,  _file );
> //do calcs here
> TA_SumStateFree(_state_copy);
> TA_SumStateFree(_state);

But this isn't efficient if copy operation is used often as it requires file I/O.
The efficient way would be to find `TA_SUM_State` definition in the library code. Copy it to your app and do something like:

> const int ssize = sizeof(struct TA_SUM_State);
> struct void* _state_copy = malloc(ssize);
> memcpy(_state_copy, _state, ssize);
> // do calcs here
> TA_SumStateFree(_state_copy);
> TA_SumStateFree(_state);

But this is a hack. The right way would be to add new function `TA_Result TA_[IND]_StateCopy(void** state_to, void** state_from)` for each indicator [IND] into TA-Lib-RT ...

**Comment by trufanov-nok** [comment]
Or... perhaps a single function that returns a size of state by its index name... like `int ssize = TA_GetSTateSize("SUM");`
What do you think?

**Comment by sunpavlik** [comment]
understand, thank you for answers

**Comment by sunpavlik** [comment]
I will be implementing this state save and reset functionality. We use the abstract interface. Noticed that the state is not just one object. State can have members, which have their own states allocated separately. So I think each function needs to have a copy function. 

I am thinking to add 3 new functions to the abstract interface:

1) clone_state()
2) copy_state()
3) reset_state()

TA_ParamHolder has hiddenData which is TA_ParamHolderPriv which has _state.

So the the reset_state() would be just reseting the _state in TA_ParamHolderPriv.

For the clone_state() and copy_state() I think I need to hook into the code generation and implement it for each function separate.

Please could you tell if this is a good plan and provide points what / how it needs to be done?

**Comment by trufanov-nok** [comment]
> TA_ParamHolder has hiddenData which is TA_ParamHolderPriv which has _state.
> So the the reset_state() would be just reseting the _state in TA_ParamHolderPriv.

There should be:

```
TA_RetCode TA_GetParamStatePtr(TA_ParamHolder *param, void**         state );
TA_RetCode TA_SetParamStatePtr(TA_ParamHolder *param,  void*           state );
```
in ta_abstract.h for that purpose.

I should think a bit about other questions.

**Comment by trufanov-nok** [comment]
Well, I've recap the code and the memcpy/sizeof way I suggested before is completely wrong. It seems I've already forgot how my own states are designed.

It seems that the right way to clone state would be adjusting gencode tool to generate one more func `*StateClone()` per each Indicator. That function shall have automatically generated code that `malloc`'s new struct, copy old struct field by field to the new struct. Then it shall check `old_struct.mem_size` and allocate `new_struct.memory = malloc(sizeof(TA_[Index]_Data)*old_struct.mem_size)` and memcpy `old_struct.memory` to `new_struct.memory`. These *.memory are arrays of `TA_[Index]_Data structs` which contain `in*` variables and represent passed input arguments history.

After that you shall manually append a few lines of code to ~25 functions.
~18 of them are just call from 1 to 3 other indicators, so they just shall initialize for ex. new_state.stateMA for BBANDS with TA_MA_StateClone(old_state.stateMA, &new_state.stateMA).

But ~7 of functions (like CCI, MFI, HT_*) use additional memory buffers allocated with `CREATE_CIRCBUF_STRUCT`  or `CREATE_CIRCBUF_STRUCT_CLASS` macro. They allocate a struct that contains arrays of specified type (like, locally defined structs) and have `.size` field to store allocated size. (I think I stored sizes of allocated arrays for `.memory` and `.circBuf`'s to Save/Load them.)

After that you have few HT_* indicators that use `CREATE_HILBERT_VARIABLES_STRUCT` macro to allocate some structs for keeping hilbert transformation calcs. I think they were organized in structs just to keep _state struct description shorter.

So you need to define a `CLONE_HILBERT_VARIABLES_STRUCT` and `CLONE_CIRCBUF_STRUCT` macro and add it to these ~ 7 functions.

Also you should modify gencode to make it generate a Frame functions for your *StateClone() functions in ta_frame.c. I think, it shall be just:
```
unsigned int TA_[INDEX]_FramePPSC( const TA_ParamHolderPriv *params, struct TA_[INDEX]_State **new_state)
{
return TA_[INDEX]_StateClone( *(struct TA_[INDEX]_State**) &params->_state, new_state);
}
```
there *SC suffix is a stands for "*StateClone"

And then add the abstract interface to these frame functions like in that commit:
https://github.com/trufanov-nok/ta-lib-rt/commit/b3f249da5125e83a02ee88f728cb8af5385e177a

It's not so difficult to do except for gencode modification is a pain. It had single function that was designed to print indicator function headers and code generated by default for them to different files (like ta_[ind].c, ta_frame.c/.h etc.), for different programming languages (c/java/.net) based on multiple flags passed into this function. It was very messy and then I added 6 more generated functions so now it's very hard to read. Also gencode partially depends on code it generates and may fail to compile after code generation in a few cases.
