### ISSUE TITLE
optInTimePeriod question

### ISSUE THREAD

**Issue by sunpavlik** [trufanov-nok/ta-lib-rt#8]
Hello, please could you clarify the meaning of optInTimePeriod? I thought the meaning is a trailing calculation window - number of data points on which the function is calculated. But when feeding data points to functions below more data points are needed than specified in optInTimePeriod to get a first calculated value. In parentheses it says how many more data points are needed. Before reaching that number of data points, "more_data" is returned.

Thank you for clarification,
Pavel

DEMA (~2x)
TEMA (~3x)
KAMA (+1)
RSI (+1)
STOCH (I remove values from the first output to match the length of the second output, I can easily undo this if you would like)
STOCHF (same thing as STOCH)
STOCHRSI (same issue again)
MOM (+1)
AROON (+1)
AROONOSC (+1)
CMO (+1)
PLUS_DI (+1)
MINUS_DI (+1)
DX (+1)
ADX (~2x)
ADXR (~3x)
ROC (+1)
ROCP (+1)
ULTOSC (+1)
TRIX (~3x)
IMI (+1)
MFI (+1)
ATR (+1)
NATR (+1)
TRANGE (+1)

**Comment by trufanov-nok** [comment]
I can give you the more detailed answer tomorrow if needed. But in short:
1. optInTimePeriod is a trailing window, but:
2. It's not equal to the data that's required to calculate the first value. Bcs some indicators are based on another indicators that'll have own trailing window. And you can't calculate high level indicator with its trailing window before underline indicator with same trailing window is calculated. For ex MA of MA with window 10 will req 10 data points to calculate first underline MA and 10 more to calc the high level MA of MA of 10 data points. So 2 x 10.
3. To get the exact number of data that is required to get first meaningful value you shall use TA_[Indicator]_Lookback(optInPeriod, ...) functions which forks for both old and new API. They actually depends only on optIn* params and are simple recursive algebraic functions.
4. The difference in behavior in new and old API is that old API will return the result array which is less than input array by N, were N is Lookback() value and actual size is returned in outNBElement argument. With new API you'll get first N results as NeedMoreData, but in both cases N is equal to Lookback() func result for given outInPeriod and other optIn* params.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by sunpavlik** [comment]
I understand points 1 - 3, but not point 4. Would it be possible to get more info?

Is there an abstract function to get the Lookback period? Or some way to accomplish it.

**Comment by trufanov-nok** [comment]
There is an abstract API to get it: `TA_GetLookback()`. It's a part of original API

**Comment by trufanov-nok** [comment]
The example could be found in testcase: https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/c/src/tools/ta_regtest/test_abstract.c#L461

**Comment by sunpavlik** [comment]
Cool, used TA_GetLookback() and here are my findings:

for SMA, set period to 8, got back lookback=7, and on the eighth call to TA_CallFuncState got the first value.

So it look like to get the actual_look_back = lookback + 1 ... correct?

Ran the same thing for ADX and got 15 and the actual is calculated the same way

**Comment by trufanov-nok** [comment]
Can't debug right now but this seems fine. You need 8-day SMA, so first result may be returned *on* 8-th day. So lookback is 7. The main meaning of a lookback func is to tell you how much space you may economize by allocating (`input_size` - `lookback`) value for result array in original API. So, it's `-7`. That's how it's should be interpreted.
