### ISSUE TITLE
Some CDL functions seem to not work

### ISSUE THREAD

**Issue by sunpavlik** [trufanov-nok/ta-lib-rt#9]
Hello,

I was testing CLD functions using the same inputs, only changing function name and some CDL functions work and some crash in TA_CallFuncState(holder). The list below is not exhaustive just a sample. Please could you tell what I am missing?

Work:
CDLKICKING
CDLHARAMI

Do not work:
CDLSPINNINGTOP
CDLSHORTLINE
CDLLONGLINE

**Comment by trufanov-nok** [comment]
could you provide a small example for, let's say CDLLONGLINE, that demonstrates the crash?

**Comment by sunpavlik** [comment]
const TA_FuncHandle *handle;
    const TA_FuncInfo *theInfo;
    TA_RetCode retCode = TA_GetFuncHandle( "CDLLONGLINE", &handle );
    if( retCode != TA_SUCCESS )
        return;

    retCode = TA_GetFuncInfo( handle, &theInfo );
    if ( retCode != TA_SUCCESS )
        return;

    TA_ParamHolder* holder;
    retCode = TA_ParamHolderAlloc(theInfo->handle, &holder);
    if ( retCode != TA_SUCCESS )
        return;

    int result;
    retCode = TA_SetOutputParamIntegerPtr(holder, 0, &result);
    if ( retCode != TA_SUCCESS )
        return;

    TA_Real price[6];
    retCode = TA_SetInputParamPricePtr(holder, 0, &price[0], &price[1], &price[2], &price[3], &price[4], &price[5]);
    if ( retCode != TA_SUCCESS )
        return;

    retCode = TA_InitNewState( holder );
    if ( retCode != TA_SUCCESS )
        return;

    price[0] = 38.16;
    price[1] = 38.165;
    price[2] = 38.16;
    price[3] = 38.165;

    retCode = TA_CallFuncState(holder);

**Comment by trufanov-nok** [comment]
You must call once `TA_Initialize();` before any access to TA-Lib's C++ API. That's by original design. Best place to call it is application's `main()`. This function initializes some global variables and seems to [set up](https://github.com/trufanov-nok/ta-lib-rt/blob/42181d2ae9c86b400b73fc3396f6a4a9fb9b6394/ta-lib-rt/c/src/ta_common/ta_global.c#L109) candle default settings.

**Comment by sunpavlik** [comment]
I see, cool, thank you
